---
project_name: rdio-scanner

release:
  extra_files:
    - glob: ./LICENSE
  github:
    owner: jodfie
    name: "{{ .ProjectName }}"

dockers:
  - image_templates:
      - "ghcr.io/jodfie/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:latest-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=GPL-3.0
      - --label=org.opencontainers.image.url=https://github.com/jodfie/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jodfie/{{ .ProjectName }}
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/jodfie/{{ .ProjectName }}:{{ .Tag }}-armv7"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}-armv7"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-armv7"
      - "ghcr.io/jodfie/{{ .ProjectName }}:latest-armv7"
    use: buildx
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=GPL-3.0
      - --label=org.opencontainers.image.url=https://github.com/jodfie/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jodfie/{{ .ProjectName }}
      - "--platform=linux/arm/v7"
  - image_templates:
      - "ghcr.io/jodfie/{{ .ProjectName }}:{{ .Tag }}-armv6"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}-armv6"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-armv6"
      - "ghcr.io/jodfie/{{ .ProjectName }}:latest-armv6"
    use: buildx
    goarch: arm
    goarm: "6"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=GPL-3.0
      - --label=org.opencontainers.image.url=https://github.com/jodfie/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jodfie/{{ .ProjectName }}
      - "--platform=linux/arm/v6"
  - image_templates:
      - "ghcr.io/jodfie/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:latest-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=GPL-3.0
      - --label=org.opencontainers.image.url=https://github.com/jodfie/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jodfie/{{ .ProjectName }}
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/jodfie/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/jodfie/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:{{ .Tag }}-armv6"
      - "ghcr.io/jodfie/{{ .ProjectName }}:{{ .Tag }}-armv7"
  - name_template: "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}-armv6"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}-armv7"
  - name_template: "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-armv6"
      - "ghcr.io/jodfie/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "ghcr.io/jodfie/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/jodfie/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/jodfie/{{ .ProjectName }}:latest-armv6"
      - "ghcr.io/jodfie/{{ .ProjectName }}:latest-armv7"

builds:
  - main: ./server
    binary: "{{ .ProjectName }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - "6"
      - "7"
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
    flags:
      - -trimpath

milestones:
  - close: true
